#!/usr/bin/env bash

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" || exit; pwd)

"$ROOT_DIR/run" -D -y down -n 10 -a && \
    "$ROOT_DIR/run" -D -y down -a && \
    "$ROOT_DIR/run" -D -y exclude && \
    "$ROOT_DIR/run" -D -y index && \
    "$ROOT_DIR/run" -D -y nav && \
    "$ROOT_DIR/run" -D -y build -a
